import { Translation } from 'primeng/api';

/**
 * PrimeNG translation for pt-BR.
 * Registered globally in app.config.ts via providePrimeNG({ translation: PRIMENG_PT_BR }).
 * All PrimeNG components (DatePicker, Table filters, FileUpload, etc.) use this automatically.
 */
export const PRIMENG_PT_BR: Translation = {
  // --- DatePicker ---
  firstDayOfWeek: 0,
  dayNames:      ['Domingo', 'Segunda-Feira', 'Terça-Feira', 'Quarta-Feira', 'Quinta-Feira', 'Sexta-Feira', 'Sábado'],
  dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  dayNamesMin:   ['Do', 'Se', 'Te', 'Qu', 'Qu', 'Se', 'Sá'],
  monthNames:      ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
  monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
  dateFormat:    'dd/mm/yy',
  weekHeader:    'Sem',
  today:         'Hoje',
  clear:         'Limpar',

  // --- Navegação do DatePicker ---
  chooseDate:  'Escolher data',
  chooseMonth: 'Escolher mês',
  chooseYear:  'Escolher ano',
  prevDecade:  'Década anterior',
  nextDecade:  'Próxima década',
  prevYear:    'Ano anterior',
  nextYear:    'Próximo ano',
  prevMonth:   'Mês anterior',
  nextMonth:   'Próximo mês',
  prevHour:    'Hora anterior',
  nextHour:    'Próxima hora',
  prevMinute:  'Minuto anterior',
  nextMinute:  'Próximo minuto',
  prevSecond:  'Segundo anterior',
  nextSecond:  'Próximo segundo',
  am: 'AM',
  pm: 'PM',

  // --- Botões de ação gerais ---
  accept:  'Sim',
  reject:  'Não',
  apply:   'Aplicar',
  cancel:  'Cancelar',
  choose:  'Escolher',
  upload:  'Enviar',

  // --- Filtros de tabela ---
  startsWith:  'Começa com',
  contains:    'Contém',
  notContains: 'Não contém',
  endsWith:    'Termina com',
  equals:      'Igual',
  notEquals:   'Diferente',
  noFilter:    'Sem filtro',
  lt:  'Menor que',
  lte: 'Menor ou igual',
  gt:  'Maior que',
  gte: 'Maior ou igual',
  is:    'É',
  isNot: 'Não é',
  before: 'Antes',
  after:  'Depois',
  dateIs:    'Data é',
  dateIsNot: 'Data não é',
  dateBefore: 'Antes de',
  dateAfter:  'Depois de',
  matchAll: 'Corresponde a todos',
  matchAny: 'Corresponde a algum',
  addRule:    'Adicionar regra',
  removeRule: 'Remover regra',

  // --- Mensagens ---
  emptyMessage:          'Nenhum resultado encontrado',
  emptyFilterMessage:    'Nenhum resultado encontrado',
  emptySelectionMessage: 'Nenhum item selecionado',
  emptySearchMessage:    'Nenhum resultado encontrado',
  pending:               'Pendente',
  searchMessage:         '{0} resultados disponíveis',
  selectionMessage:      '{0} itens selecionados',

  // --- FileUpload ---
  fileChosenMessage:   '{0} arquivo(s) selecionado(s)',
  noFileChosenMessage: 'Nenhum arquivo selecionado',

  // --- Password ---
  weak:           'Fraca',
  medium:         'Média',
  strong:         'Forte',
  passwordPrompt: 'Digite uma senha',

  // --- Aria labels ---
  aria: {
    trueLabel:    'Verdadeiro',
    falseLabel:   'Falso',
    nullLabel:    'Não selecionado',
    close:        'Fechar',
    previous:     'Anterior',
    next:         'Próximo',
    navigation:   'Navegação',
    scrollTop:    'Ir ao topo',
    moveTop:      'Mover para o início',
    moveUp:       'Mover para cima',
    moveDown:     'Mover para baixo',
    moveBottom:   'Mover para o fim',
    pageLabel:    'Página {page}',
    firstPageLabel:    'Primeira página',
    lastPageLabel:     'Última página',
    nextPageLabel:     'Próxima página',
    prevPageLabel:     'Página anterior',
    previousPageLabel: 'Página anterior',
    rowsPerPageLabel:  'Linhas por página',
    jumpToPageDropdownLabel: 'Ir para página',
    jumpToPageInputLabel:    'Ir para página',
    selectRow:    'Selecionar linha',
    unselectRow:  'Desmarcar linha',
    expandRow:    'Expandir linha',
    collapseRow:  'Recolher linha',
    selectAll:    'Selecionar todos',
    unselectAll:  'Desmarcar todos',
    showFilterMenu:  'Mostrar menu de filtro',
    hideFilterMenu:  'Ocultar menu de filtro',
    filterOperator:  'Operador de filtro',
    filterConstraint: 'Restrição de filtro',
    editRow:    'Editar linha',
    saveEdit:   'Salvar edição',
    cancelEdit: 'Cancelar edição',
    listView:   'Visualização em lista',
    gridView:   'Visualização em grade',
    zoomImage:  'Ampliar imagem',
    zoomIn:     'Aumentar zoom',
    zoomOut:    'Diminuir zoom',
    rotateRight: 'Girar para direita',
    rotateLeft:  'Girar para esquerda',
    listLabel:   'Lista de opções',
    browseFiles: 'Procurar arquivos',
    maximizeLabel: 'Maximizar',
  }
};
